server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file:///Users/js/Desktop/github/git-local-repo
          uri: https://github.com/shk3029/study-spring-cloud-config-repository.git
          #username:
          #password: